package io.casehub.openclaw.app.example;

import java.util.UUID;

import jakarta.enterprise.context.ApplicationScoped;
import jakarta.inject.Inject;
import jakarta.transaction.Transactional;

import io.casehub.openclaw.casehub.OpenClawAgentRegistry;
import io.casehub.openclaw.casehub.OpenClawCaseChannelProvider;
import io.casehub.openclaw.context.ChannelContextWindowService;
import io.casehub.platform.api.identity.ActorType;
import io.casehub.qhorus.api.message.MessageDispatch;
import io.casehub.qhorus.api.message.MessageType;
import io.casehub.qhorus.runtime.message.MessageService;

/**
 * Transactional setup delegate for ExampleController.
 *
 * <p>Handles all JPA-touching operations in a single transaction: channel creation,
 * agent registry update, ChannelContextWindow binding, and COMMAND dispatch. The
 * JAX-RS handler itself is not @Transactional — this bean owns the transaction boundary
 * for the setup phase.
 *
 * <p>commandContent is the base task description only. buildPrompt() in
 * OpenClawChannelBackend.post() automatically appends the full CaseHub commitment
 * context block (commitmentId, casehub_done invocation) when correlationId is non-null.
 * Do NOT embed commitmentId in commandContent.
 *
 * <p>correlationId is generated by ExampleController before calling this method so the
 * caller can poll on it via ExamplePoller.checkState().
 */
@ApplicationScoped
class ExampleSetup {

    private final OpenClawCaseChannelProvider caseChannelProvider;
    private final OpenClawAgentRegistry registry;
    private final ChannelContextWindowService contextService;
    private final MessageService messageService;

    @Inject
    ExampleSetup(final OpenClawCaseChannelProvider caseChannelProvider,
                 final OpenClawAgentRegistry registry,
                 final ChannelContextWindowService contextService,
                 final MessageService messageService) {
        this.caseChannelProvider = caseChannelProvider;
        this.registry = registry;
        this.contextService = contextService;
        this.messageService = messageService;
    }

    /**
     * Creates (idempotent) channels for the demo caseId, registers the agent, and
     * dispatches a COMMAND to the work channel.
     *
     * <p>openChannel() is idempotent — finds existing channels by name — so calling
     * this for successive agents in the same run only updates registry and bindAgent().
     */
    @Transactional
    void setupAndDispatch(final UUID caseId, final String tenancyId,
                          final String agentId, final String sessionKey,
                          final String correlationId, final String commandContent) {
        // openChannel() is idempotent (finds existing channel by name) and returns the CaseChannel.
        // Capture the work channel UUID from the return value to avoid a subsequent listChannels() call.
        final UUID workChannelId = UUID.fromString(
                caseChannelProvider.openChannel(caseId, "work").id());
        caseChannelProvider.openChannel(caseId, "observe");
        caseChannelProvider.openChannel(caseId, "oversight");

        registry.register(agentId, tenancyId, caseId, sessionKey);
        contextService.bindAgent(agentId, caseId);

        messageService.dispatch(MessageDispatch.builder()
                .channelId(workChannelId)
                .sender("example-controller")
                .type(MessageType.COMMAND)
                .content(commandContent)
                .correlationId(correlationId)
                .actorType(ActorType.SYSTEM)
                .build());
    }
}
